### ISSUE TITLE
Compiling Issues on Ubuntu

### ISSUE THREAD

**Issue by Exodius** [WoWSource/WoWSource434#1]
Compiling fails with these errors.

```
[  0%] Building CXX object dep/StormLib/CMakeFiles/storm.dir/src/adpcm/adpcm.cpp.o
Scanning dependencies of target gamePCH.cpp_dephelp
[  0%] Building CXX object src/server/game/CMakeFiles/gamePCH.cpp_dephelp.dir/PrecompiledHeaders/gamePCH.cpp.o
Scanning dependencies of target ScriptPCH.cpp_dephelp
[  0%] Building CXX object src/server/scripts/CMakeFiles/ScriptPCH.cpp_dephelp.dir/PrecompiledHeaders/ScriptPCH.cpp.o
In file included from /home/cataclysm/WoWSource434-1/dep/jemalloc/include/jemalloc/internal/jemalloc_internal.h:568:0,
                 from /home/cataclysm/WoWSource434-1/dep/jemalloc/src/arena.c:2:
/home/cataclysm/WoWSource434-1/dep/jemalloc/include/jemalloc/internal/util.h:88:49: error: expected ‘;’, ‘,’ or ‘)’ before ‘nptr’
 uintmax_t malloc_strtoumax(const char *restrict nptr,
                                                 ^
[  0%] [  0%] Building CXX object dep/StormLib/CMakeFiles/storm.dir/src/huffman/huff.cpp.o
Building CXX object dep/recastnavigation/Detour/CMakeFiles/Detour.dir/DetourCommon.cpp.o
[  0%] [  0%] Building CXX object dep/recastnavigation/Recast/CMakeFiles/Recast.dir/RecastArea.cpp.o
Building CXX object dep/recastnavigation/Detour/CMakeFiles/Detour.dir/DetourNavMesh.cpp.o
make[2]: *** [dep/jemalloc/CMakeFiles/jemalloc.dir/src/arena.c.o] Error 1
make[1]: *** [dep/jemalloc/CMakeFiles/jemalloc.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

Ubuntu 12.10 server
gcc (GCC) 4.8.2
cmake version 2.8.12.2

**Comment by Talmeron** [comment]
Linux in General. Also required ACE be installed...which is no longer in the TC howto.

In Fedora 21, the error is:

Scanning dependencies of target jemalloc
[  0%] Building C object dep/jemalloc/CMakeFiles/jemalloc.dir/src/arena.c.o
In file included from /home/exaurdon/WoWSource434/dep/jemalloc/include/jemalloc/internal/jemalloc_internal.h:568:0,
                 from /home/exaurdon/WoWSource434/dep/jemalloc/src/arena.c:2:
/home/exaurdon/WoWSource434/dep/jemalloc/include/jemalloc/internal/util.h:88:49error: expected ‘;’, ‘,’ or ‘)’ before ‘nptr’
 uintmax_t malloc_strtoumax(const char _restrict nptr,
                                                 ^
dep/jemalloc/CMakeFiles/jemalloc.dir/build.make:54: recipe for target 'dep/jemalloc/CMakeFiles/jemalloc.dir/src/arena.c.o' failed
make[2]: *_\* [dep/jemalloc/CMakeFiles/jemalloc.dir/src/arena.c.o] Error 1
CMakeFiles/Makefile2:133: recipe for target 'dep/jemalloc/CMakeFiles/jemalloc.dir/all' failed
make[1]: **\* [dep/jemalloc/CMakeFiles/jemalloc.dir/all] Error 2
Makefile:117: recipe for t

**Comment by Igorinus** [comment]
guys update your  libaries http://s10.postimg.org/ujbi0nm3t/12325.png

**Comment by Bulbucan** [comment]
You have to update your Linux libraries.
Update your g++ and gcc to version 4.8
I have Debian and I can compile 100% fine with this version.

**Comment by Exodius** [comment]
As I already wrote in main report...

```
Ubuntu 12.10 server edition
gcc (GCC) 4.8.2
cmake version 2.8.12.2
```

```
# gcc --version
gcc (GCC) 4.8.2
# g++ --version
g++ (GCC) 4.8.2
```

**Comment by Talmeron** [comment]
I'm at 4.9

**Comment by Bulbucan** [comment]
/home/cataclysm/WoWSource434-1/dep/jemalloc/include/jemalloc/internal/util.h:88:49: error: expected ‘;’, ‘,’ or ‘)’ before ‘nptr’
 uintmax_t malloc_strtoumax(const char *restrict nptr,
What you don't understand here? Type nptr;
and will solve your problem.

**Comment by Talmeron** [comment]
So by saying it expects ; BEFORE nptr, I should put it AFTER nptr.

**Comment by Myst** [comment]
I compiled without any error, update ALL your libraries.

**Comment by Talmeron** [comment]
Looking on the forums, this has been an issue since July 2014.

**Comment by vanasis** [comment]
There is No problem in compiling Linux

**Comment by Talmeron** [comment]
Thanks for fixing the issues, since all my libraries are updated. Maybe testing on Ubuntu to see what the problem may be instead of just saying there isn't a problem would be the better way to deal with it.

**Comment by Myst** [comment]
I just donwloaded the source and compiled without any problem, some VIP's have the source running on their servers

**Comment by Igorinus** [comment]
this is not the vip repo or version but is working compile 100% in linux

**Comment by Myst** [comment]
I also downloaded this source and I never got any problem compiling.

**Comment by Exodius** [comment]
@vanasis It's nice to claim that <b><i>There is No problem in compiling Linux</i></b> while some of us still have problems compiling even with updated libraries.

@Talmeron even has problems on Fedora.

Interesting fact:
Same problem exists on your release from few days ago (repo that was deleted and that I cloned in meantime) https://github.com/Exodius/WoWSource434-1

That same compile error exists on a V8 "leak" https://github.com/aikonlee/WoWSource434
Bug report was submitted even on that one: https://github.com/aikonlee/WoWSource434/issues/2

The fact that it does not compile on some distros means that problem exists somewhere.

**Comment by vanasis** [comment]
we have users that use in linux if u like i can upload photo here . i belive u do something wrong
Best regards

**Comment by Talmeron** [comment]
In Fedora, since it uses 4.9 GCC and C++ have to download 4.8 and then using the cmake gui (I'm lazy) click configure--click choose native compiler-for c and c++ look in /usr/bin for the gcc-4.8 and c++-4.8 and the it will compile. (Debian 8 and Fedora are at 4.9 now, so that likely will be an issue that needs to be fixed soonish)

**Comment by Myst** [comment]
can you paste your compiling flags?

**Comment by Kaned1as** [comment]
It's dead simple, guys.

the default C flags GCC uses is still -std=gnu89. For the source to compile properly you need to specify explicit -std=gnu11 in CMAKE_C_FLAGS. If you use ccmake, just do

`ccmake ..`, press `t` to go in advanced mode, find `CMAKE_C_FLAGS`, press `Enter` to edit it, write `-std=gnu11`, press `Enter` again. Then press `c` and then `e` and `g` to generate makefiles. Then just run `make` as usual.

And remember, those who shout _"There is No problem in compiling Linux"_, you are not the entire world. Works-for-me was never an answer for any good developer.

**Comment by Myst** [comment]
Plobably what he mean was that the source is not the problem.

**Comment by Bulbucan** [comment]
For sure the problem is in source, because I have last TrinityCore to, and I have all libraries ok.
Compiling is perfect but I can't start them. If you don't have good libraries in linux u can't compile it.
